### ISSUE TITLE
Break up All-In-One Sketch File into a separate Sketch File per App area

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/DesignInventory#9]
In DesignInventory/Ballot [here](https://github.com/wevote/DesignInventory/tree/master/Ballot) there is a file called "WeVoteWires-20181207-AaronT-v05.sketch". This contains the work of our Experience Director, with designs from various areas of the We Vote app.

Please make copies of this file (using the naming convention [described here under "Asset File Naming Standards"](https://github.com/wevote/DesignInventory/blob/master/README.md), and put them in the relevant folders in the DesignInventory folder (The DesignInventory folder can be interacted with via Github, or it is within this Google Drive Design folder: https://drive.google.com/drive/u/2/folders/0BwSkwvLXQCocQlhhVzF2U2FfZXc )
Please move designs not relevant to the new filename off to the side (or delete if completely unrelated).

Files I know we will need include: 
- [ ] Candidate related designs would go into a file with this name: DesignInventory/Ballot/Candidates/CandidateDetail-20181221-AaronT-Yuan-v1.sketch
- [ ] Measure related designs would go into a file with this name: DesignInventory/Ballot/Measures/Measures-20181221-AaronT-Yuan-v1.sketch

**Comment by jlev** [comment]
Please also break the issue icons out into symbols, so they can be reused across Sketch files, without having to download TTFs for each icon library.

**Comment by DaleMcGrew** [comment]
Done!

**Comment by yuanhsinchang** [comment]
Hi Dale,

Sorry for replying back so late. I will check the issue and finish it as
soon as possible.

Sincerely,
Yuan
